### ISSUE TITLE
[Feature]: Sub directory support

### ISSUE THREAD

**Issue by freitagdavid** [alucryd/oxyromon#38]
Would there be any possibility of supporting sub directories in the rom folder eg 'redump/Sony - PlayStation' it's really nice for organization to be able to break stuff down into subdirs like that.

**Comment by alucryd** [comment]
What would be the use case? Be able to have a folder of PSP roms verified by redump, and another folder verified by nointro for example?

**Comment by freitagdavid** [comment]
That is definitely one use case though for most who use this style of folder layout it's more just for general organization. If you have the entire no-intro, and entire redump collection it just makes it a bit cleaner if you keep them separated since in many cases you treat these different sets in slightly different ways.

**Comment by alucryd** [comment]
Something similar can now be achieved using the `GROUP_SUBSYSTEMS` setting. With it set to `false`, separate DATs for the same system will be stored in separate directories (provided they don't share the same name, otherwise, they'll just overwrite one another). For example, this would apply `Sony - PlayStation Portable (Redump)` and `Sony - PlayStation Portable (No-Intro)`. It works also on DLCs and updates for the various consoles that have eShops.
