### ISSUE TITLE
Error when No Match is found

### ISSUE THREAD

**Issue by aarongeorge** [alucryd/oxyromon#49]
When importing the No-Intro GBA set, this error is thrown when a match isn't found

```bash
No match
Moving to "~/Emulation/Nintendo - Game Boy Advance/Trash/Action Replay MAX (Europe) (Unl).gba"
thread 'main' panicked at 'Error while creating romfile: Database(SqliteError { code: 2067, message: "UNIQUE constraint failed: romfiles.path" })', src/database.rs:1432:6
```

**Comment by alucryd** [comment]
Thanks for the bug report. This has been on my backlog for a while, basically this happens when you've already tried and failed to import a file with the same name, the two options I have is to rename the second with a different name, or just overwrite the previous file in the trash directory. I'm leaning towards the latter because if the previous file failed to validate you probably don't want it anyway. I'll fix that in the develop branch this week if time allows.

**Comment by alucryd** [comment]
Had some time this evening, I just published version `0.13.0` with a fix. Please let me know if that works for you.

Note that this version changes the way archives are named, they no longer contain the original file extension as it created compatibility issues with retroarch.

**Comment by aarongeorge** [comment]
Thanks mate, will compile and test now

**Comment by aarongeorge** [comment]
Worked a treat!
