### ISSUE TITLE
[Feature] Use already imported CUE file when importing CHD

### ISSUE THREAD

**Issue by TylerVigario** [alucryd/oxyromon#57]
It would be awesome if oxyromon would make use of already imported .cue files for CHD files imported after the CUE file.

**Comment by alucryd** [comment]
That's something I ultimately decided against because the only data you have is the CHD name, so if your CHD isn't named exactly like in the database of your choice, there is no way to retrieve the correct CUE. I could add a selector like I do for PS3 though, that's something to consider. Requiring the CUE at import time is the only surefire way to get it right without additional input from the user, and it allows for a different name from the database, as long as the CHD and CUE are named identically.

Another option would be to add an additional flag to the import command pointing to the correct CUE.

**Comment by TylerVigario** [comment]
> Another option would be to add an additional flag to the import command pointing to the correct CUE.

How about not importing a CUE that doesn't have a matching CHD at import time?

**Comment by alucryd** [comment]
It's possible people will later import regular BINs, or even at the same time, so importing CUEs alone is a valid use case.

When importing CHDs, you should not list the CUE in the command line, as it will automatically be picked up. In case either the CUE or CHD don't match, nothing is imported. They are imported only if both match.

**Comment by TylerVigario** [comment]
> It's possible people will later import regular BINs, or even at the same time, so importing CUEs alone is a valid use case.

Ahh, I forgot CUEs are useful for regular BINs. Thanks for reminding me!

I don't imagine it would hurt to check during import if a ROM name matches a possibly already imported CUE file. After all it can be so crucial to the CHD import procedure.

However, this isn't a biggie. I learned to keep CUE files with CHDs now, anyway.

**Comment by alucryd** [comment]
Yeah, I'll add that to the backlog, thanks.
