### ISSUE TITLE
[Minor Issue] Dolphin file naming on Windows

### ISSUE THREAD

**Issue by jdc0730** [alucryd/oxyromon#80]
Using the tool on Windows. When performing RVZ functions, the software is looking for dolphin-tool. In the windows installation of Dolphin the file is named DolphinTool.exe.  As a workaround, I made a copy of DolphinTool named dolphin-tool and everything operates as expected.

**Comment by alucryd** [comment]
There you go: https://github.com/alucryd/oxyromon/commit/c7b717a485d0e8699e02f197980358c855a6676d

I can build a test exe if you'd like.

**Comment by jdc0730** [comment]
If you’d like me to confirm, then yes, a test build would be appreciated. Sent from my iPhoneOn May 16, 2023, at 5:05 PM, Maxime Gauduin ***@***.***> wrote:﻿
There you go: c7b717a
I can build a test exe if you'd like.

**Comment by alucryd** [comment]
Here's a test build: https://mega.nz/file/UGgEDCDJ#Es45JJCMJGAQVHs754nVOWnxsnI6ItkLeE20R3gmgNE

**Comment by alucryd** [comment]
Thanks for the kind words. No problem, here's a new link, it contains the language filter as well: https://mega.nz/file/Zeo0lYDa#6_taQRKu1jFFQVmFhDt01wDQ2dligMykhARo2FAoGpw

I have no control over the expiry date since I'm using a free account, but it should last forever unless I replace the file (which I suspect is what happened since I pushed an updated file for the language filter some time after).

**Comment by jdc0730** [comment]
I was able to download the file and can confirm it is able to find the Windows executable. I will look to test the language bit tomorrow.
